name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - supabase_merwane
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install UV Package Manager
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set Up Virtual Environment
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e .

      - name: Format Check with Black
        run: |
          source .venv/bin/activate
          black ./src/
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install UV Package Manager
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set Up Virtual Environment
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e .

      - name: Run Tests with Pytest
        run: |
          source .venv/bin/activate
          pytest tests/
